### ISSUE TITLE
Support converting modules

### ISSUE THREAD

**Issue by clstokes** [pulumi/tf2pulumi#239]
Add support for TF modules

### Work Items

- [x] [Add module support for PCL](https://github.com/pulumi/pulumi/pull/12361)
- [x] [.NET programgen](https://github.com/pulumi/pulumi/pull/12361)
- [x] [Convert TF modules to PCL components](https://github.com/pulumi/tf2pulumi/issues/275)
- [x] [Node.js programgen](https://github.com/pulumi/pulumi/pull/12398)
- [x] [Python programgen](https://github.com/pulumi/pulumi/pull/12555)
- [x] [Go programgen](https://github.com/pulumi/pulumi/pull/12840)

### Later
- [ ] [Java programgen](https://github.com/pulumi/pulumi-java/issues/1100)
- [ ] YAML programgen (depends on support for YAML components)

**Comment by Nezteb** [comment]
Modules are a pretty commonly used feature of Terraform, so I imagine many people will run into this issue when attempting to migrate. Until `tf2pulumi` is able to convert modules (either partially or in their entirety), it'd probably be useful to add a disclaimer on the various pages that reference `tf2pulumi` about this unsupported functionality:
- https://www.pulumi.com/docs/intro/vs/terraform/
- https://www.pulumi.com/docs/guides/adopting/from_terraform/
- https://www.pulumi.com/docs/intro/vs/terraform/
- https://www.pulumi.com/tf2pulumi/

I'd also consider it a reasonable stopgap to have `tf2pulumi` generate some sort of stub file/package for each HCL2 module it detects. At least something to give developers a starting point to work from? 😅 

Also if anyone at Pulumi has manually converted a Terraform stack with modules to work in Pulumi, perhaps a blog post (or series of posts) would be useful? I'll be time-boxing some work on converting a couple Terraform stacks to Pulumi at work, and depending on how that goes I might write a blog post myself on the subject. 😄

**Comment by justinvp** [comment]
I'm going to close this as complete. The new TF converter supports converting modules to PCL components and all the main Pulumi languages now support emitting components from PCL.

https://github.com/pulumi/pulumi-java/issues/1100 tracks adding support to Java.
