### ISSUE TITLE
[Epic] tf2pulumi improvements

### ISSUE THREAD

**Issue by justinvp** [pulumi/tf2pulumi#264]
## Overview

We want tf2pulumi to be a great way to migrate users from terraform to pulumi. It is currently very under-developed, can't handle many examples, has target language specific bugs, and in general could do with load of work. This epic is to track making tf2pulumi great for _most_ customer migrations, by finishing work started to support the majority of built-in TF functions, support modules, and modern TF features.

### References 📔

- [Internal channel](https://pulumi.slack.com/archives/C047FKH1N2D)

### M84

- [ ] Publish pulumi-std
- [ ] https://github.com/pulumi/pulumi-std/issues/17
- [ ] Update tf2pulumi to call functions in pulumi-std 

### M85

- [ ] Modules (started in M83)
- [ ] https://github.com/pulumi/tf2pulumi/issues/186
