### ISSUE TITLE
Python Backend Bringup Meta-Issue

### ISSUE THREAD

**Issue by swgillespie** [pulumi/tf2pulumi#98]
This issue tracks the bringup of the Python backend of tf2pulumi.

## Known NYIs

* [ ] https://github.com/pulumi/tf2pulumi/issues/97 Exact Map Properties
* [ ] https://github.com/pulumi/tf2pulumi/issues/96 List Properties
* [ ] https://github.com/pulumi/tf2pulumi/issues/95 Indexing
* [ ] https://github.com/pulumi/tf2pulumi/issues/94 Conditionals
* [ ] https://github.com/pulumi/tf2pulumi/issues/93 Intrinsic Call
* [ ] https://github.com/pulumi/tf2pulumi/issues/92 Arithmetic
* [ ] https://github.com/pulumi/tf2pulumi/issues/91 Outputs
* [ ] https://github.com/pulumi/tf2pulumi/issues/90 Data Sources
* [ ] https://github.com/pulumi/tf2pulumi/issues/89 Explicit Dependencies
* [ ] https://github.com/pulumi/tf2pulumi/issues/88 Locals
* [ ] https://github.com/pulumi/tf2pulumi/issues/87 Modules
* [ ] https://github.com/pulumi/tf2pulumi/issues/86 String Literals

## Known Bugs

None (yet!)

We're bringing up the Python backend pragmatically, implementing NYIs as we need them and not any earlier.

**Comment by lukehoban** [comment]
Closing out in favor of https://github.com/pulumi/pulumi/issues/4332.
